import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'answer_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'answer_model.g.dart';

@freezed
class AnswerModel with _$AnswerModel {
  const factory AnswerModel({
    required int id,
    required String nameAz,
    required String nameRu,
    required String nameEn,
  }) = _AnswerModel;

  factory AnswerModel.fromJson(Map<String, Object?> json)
  => _$AnswerModelFromJson(json);
}