import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'question_correct_answer_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'question_correct_answer_model.g.dart';

@freezed
class QuestionCorrectAnswerModel with _$QuestionCorrectAnswerModel {
  const factory QuestionCorrectAnswerModel({
    required int id,
    required int answerNo
  }) = _QuestionCorrectAnswerModel;

  factory QuestionCorrectAnswerModel.fromJson(Map<String, Object?> json)
  => _$QuestionCorrectAnswerModelFromJson(json);
}