import 'package:drive_license_app/models/question_answer_model.dart';
import 'package:drive_license_app/models/question_correct_answer_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'question_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'question_model.g.dart';

@freezed
class QuestionModel with _$QuestionModel {
  const factory QuestionModel({
    required int id,
    required String nameAz,
    required String nameRu,
    required String nameEn,
    String? imagePath,
    required List<QuestionAnswerModel> questionAnswer,
    required QuestionCorrectAnswerModel correctAnswer,
  }) = _QuestionModel;

  factory QuestionModel.fromJson(Map<String, Object?> json)
  => _$QuestionModelFromJson(json);
}